### PR TITLE
Create renegades.catpkg.yml

### PR DESCRIPTION
**Pull request by StaffanBoffins**
New Gamesystem for skirmsh game Renegades.

### CODE REVIEW

**Comment by Mad-Spy** [comment]
There is no such repository in the BSData org. If you are trying to add a repository you have in your private org, the file needs to point there.

**Comment by StaffanBoffins** [comment]
Ok, my bad. Maybe I should clone your repo instead?

**Comment by Mad-Spy** [comment]
What are you trying to achieve?

**Comment by StaffanBoffins** [comment]
I want to add a new game system for a skirmish game called Renegades.
https://www.playrenegades.com/

**Review by StaffanBoffins — COMMENTED** [review]
Changed to correct org.

**Review by StaffanBoffins — COMMENTED** [review]
Added topic.

**Comment by StaffanBoffins** [comment]
Is there anything else I need to do to get the gamesystem into the
repository?

Den sön 5 maj 2024 20:24Iain Launchbury ***@***.***> skrev:

**Comment by Mad-Spy** [comment]
You'll need to have your Battlescribe pull from Gallery instead of the default source as per the instructions in the Gallery readme. 

If you're using NR, you can just add the data direct from Github, using the "Add from Github" option when adding a new system.

**Comment by StaffanBoffins** [comment]
Ok, done that. One last question, the title of the gamesystem was wrong (Description in the repo) so I changed it to "Renegades v3". Do I need to do another PR for that change?

**Comment by Mad-Spy** [comment]
No. It'll change after your next release.

**Pull request merged**
