### PR TITLE
Create starbreach.catpkg.yml

### PR DESCRIPTION
**Pull request by andreanespeca**
let me know if this is what you are after

### CODE REVIEW

**Comment by amis92** [comment]
First of all, thank you for patience - I'll need more of that, however, as we progress through some changes required in your repository (and maybe on our side as well).

1. Please save all files as unzipped `.cat`/`.gst` files.
2. Please accept the PR the bot will create. This will result in GH Actions adding necessary assets to releases you make.

**Comment by andreanespeca** [comment]
All done let me know if i need to do anything else
Thanks

**Comment by amis92** [comment]
@andreanespeca it'd be nice if you had added a readme - but it's not *necessary*.

Now, let's see if this works...

**Comment by amis92** [comment]
Ah, I know - @andreanespeca you'll need to create a new release now as well, so see the repo on our Gallery 👍

**Comment by andreanespeca** [comment]
All done let's see if it works!

**Pull request merged**
