### PR TITLE
Create TOW.catpkg.yml

### PR DESCRIPTION
**Pull request by Birddie721**
Adds file to support Warhammer: The Old World in Battlescribe

### CODE REVIEW

**Comment by Mad-Spy** [comment]
The Old World is already supported via New Recruit. We will not be adding it to Battlescribe.

**Comment by Birddie721** [comment]
So because it's available on another app, you won't add it to yours? I have the data all created for Battlescribe already, ready to be added. I don't understand why just because it's available elsewhere you won't add it to your platform.

**Comment by Mad-Spy** [comment]
Battlescribe is not "our app". It was abandoned by its developer over 4 years ago. The data author community is actively encouraging users to move away from Battlescribe to an alternative and currently we recommend New Recruit. The majority of active data developers no longer use the BS data editor in favour of New Recruit. New Recruit is being actively supported by its developers and has many enhancements over Battlescribe functionality.

When the question of The Old World dataset was brought up in the Data Author Discord, the decision was made that it would be the first mainstream dataset to be written utilising all of the new features available in New Recruit and would therefore be incompatible with Battlescribe. The first version was released a month ago. Thus, there is already a large userbase of that dataset in New Recruit and we are encouraging new users to use it. It is unfortunate that you didn't mention that you were working on Old World data in our Discord as we could have passed on this information to you.

Making another dataset available for the same game would lead to confusion for users and so we would prefer not to do so. I understand that this decision will be disappointing for you given the work that you have put in. It's possible that the current maintainers for the Old World data would welcome your experience in assisting with maintaining it in future. You can contact them via the New Recruit Discord.

**Comment by Birddie721** [comment]
Ok, thank you for the explanation. I did not know that BattleScribe was abandoned. I know a lot of people live in the past, like me, so I will still make my BattleScribe TOW available through my Github link, but I understand why your decision was made.

**Pull request closed without merging**
